version: '3.8'

services:
  gemba_database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  data-volume:
    name: gemba_database_data_volume