name: Deploy Frontend to Development

on:
  push:
    branches: [develop]
    paths:
      - 'apps/web/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloudCLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Config Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast2-docker.pkg.dev

      - name: Build Frontend Docker image (linux/amd64)
        run: |
          docker build -t asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gemba-frontend-dev/gemba-frontend-dev:latest \
            --platform linux/amd64 \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            --build-arg NEXT_PUBLIC_GOOGLE_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }} \
            --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }} \
            --build-arg NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }} \
            --build-arg NEXT_PUBLIC_TIMEZONE=Asia/Tokyo \
            -f apps/web/docker/Dockerfile .

      - name: Push Frontend Docker image
        run: |
          docker push asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gemba-frontend-dev/gemba-frontend-dev:latest

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: gemba-frontend-dev
          image: asia-northeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gemba-frontend-dev/gemba-frontend-dev:latest
          region: asia-northeast2
          env_vars: |
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
            AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}
            AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          flags: |
            --allow-unauthenticated
